intelli-muscle-mountain/sweet

app/controllers/customers_controller.rb
app/views/customers/edit.html.erb
app/views/customers/show.html.erb
app/views/customers/withdraw.html.erb
config/routes.rb

#会員用のマイページ、詳細、編集、退会ページを作成。
#ルートにtopページにアクセスできるように設定。

[Add]customers_mypage

---

app/controllers/admins/customers_controller.rb
app/controllers/admins/items_controller.rb
app/controllers/customers_controller.rb
app/views/admins/customers/edit.html.erb
app/views/admins/customers/index.html.erb
app/views/admins/customers/show.html.erb

Admin-customerpage

---

app/controllers/admins/genres_controller.rb
app/views/admins/genres/edit.html.erb
app/views/admins/genres/index.html.erb
app/views/customers/registrations/new.html.erb

ジャンルコントローラーと一覧画面・編集画面を追加しましたがエラー出てます。

genre&admin-SignUp add

---

app/controllers/admins/genres_controller.rb
app/views/admins/genres/index.html.erb

[Fix]genre-index&controller

---

app/controllers/application_controller.rb

application_controller

---

app/views/admins/genres/edit.html.erb
app/views/customers/registrations/new.html.erb

管理者側の登録ページ編集

---

db/migrate/20200208082709_change_column_customer.rb

#Customer作成時にcustomer_statusにtrueがデフォルトで入るよう設定

[Change]customer-status-default

---

app/controllers/admins/genres_controller.rb
app/views/admins/genres/edit.html.erb
app/views/admins/genres/index.html.erb
db/migrate/20200208102312_change_genre_status_to_genre.rb

げんれを使える様にしました

---

app/controllers/admins/customers_controller.rb
app/controllers/customers_controller.rb
app/models/customer.rb
app/views/admins/customers/edit.html.erb
app/views/admins/customers/index.html.erb
app/views/admins/customers/show.html.erb
app/views/customers/edit.html.erb
app/views/customers/show.html.erb
app/views/customers/withdraw.html.erb
config/routes.rb

[Add]admin-customer-withdraw

---

app/controllers/admins/customers_controller.rb
app/controllers/admins/genres_controller.rb
app/controllers/admins_controller.rb
app/controllers/customers_controller.rb
app/models/customer.rb
app/views/admins/genres/edit.html.erb
app/views/admins/top.html.erb
app/views/customers/withdraw.html.erb
config/routes.rb

[add]customer-withdraw

---

app/assets/stylesheets/application.scss
app/views/admins/customers/edit.html.erb
app/views/admins/customers/index.html.erb
app/views/admins/customers/show.html.erb

[add]admin-customer-style

---

config/routes.rb

#ルートにmemberを導入することにより少しきれいにしました

[Add]routes-member

---

app/controllers/customers_controller.rb
app/views/admins/customers/show.html.erb
app/views/customers/show.html.erb
app/views/customers/withdraw.html.erb
config/routes.rb

[fix]customer-withdraw

---

app/controllers/customers_controller.rb

[fix]customer-controller

---

app/assets/stylesheets/application.scss
app/views/customers/edit.html.erb
app/views/customers/show.html.erb
app/views/customers/withdraw.html.erb

[add]customer-style

---

app/assets/stylesheets/admins/customers.scss
app/assets/stylesheets/admins/genres.scss
app/assets/stylesheets/application.scss
app/views/admins/_link.html.erb
app/views/admins/genres/edit.html.erb
app/views/admins/genres/index.html.erb

[add]genre-layout

---

app/assets/stylesheets/admins/genres.scss

[fix]genre-layout

---

app/assets/stylesheets/admins/items.scss
app/views/admins/items/edit.html.erb
app/views/admins/items/index.html.erb
app/views/admins/items/new.html.erb
app/views/admins/items/show.html.erb

[add]admin-item-layout

---

app/controllers/cartitems_controller.rb

#cartitemコントローラ内のindexアクションを[customer_id: current_customer.id]に変更しました

[fix]customer-cartitem-controller

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/cartitems.scss
app/controllers/items_controller.rb
app/views/cartitems/index.html.erb
app/views/items/show.html.erb

[add]cartitem-index&customer-item-show--layout

---

app/views/customers/registrations/new.html.erb
app/views/customers/sessions/new.html.erb

#カスタマー側のログイン、サインアップ画面のレイアウト調整しました

[add]customer-login&signup-layout

---

app/assets/stylesheets/application.scss
app/controllers/admins/items_controller.rb
app/views/customers/_link.html.erb
app/views/items/about.html.erb
app/views/layouts/application.html.erb

[add]header&footer-layout

---

app/views/customers/show.html.erb

[fix]customer-mypage

---

app/controllers/orders_controller.rb
app/views/orders/confirm.html.erb

[fix]order-indent

---

app/views/orders/confirm.html.erb

[fix]confirm

---

app/controllers/admins/orders_controller.rb
app/controllers/orders_controller.rb
app/views/admins/_link.html.erb

#管理者側の注文一覧ページを、直接URL打っても見れるようにしました

[fix]admin-order-index

---

app/models/address.rb
app/views/orders/confirm.html.erb
app/views/orders/new.html.erb

[fix]layout

---

app/controllers/items_controller.rb
app/views/admins/items/edit.html.erb
app/views/items/index.html.erb

#商品一覧でジャンル検索できるようにしました。
#ジャンル無効、商品売り切れのものは表示されないようにしました

[add]genre-search

---

app/controllers/addresses_controller.rb
app/controllers/admins/customers_controller.rb
app/controllers/admins/genres_controller.rb
app/controllers/admins/items_controller.rb
app/controllers/admins/orders_controller.rb
app/controllers/admins_controller.rb
app/controllers/application_controller.rb
app/controllers/cartitems_controller.rb
app/controllers/customers_controller.rb
app/controllers/items_controller.rb
app/controllers/orders_controller.rb
app/models/item.rb
app/models/order.rb
app/views/admins/orders/show.html.erb
app/views/customers/_link.html.erb
app/views/items/show.html.erb
app/views/orders/show.html.erb

未ログイン時の画面遷移の制限をかけました

---

app/controllers/admins/customers_controller.rb

[fix]admin-customer-controller

---

app/controllers/cartitems_controller.rb
app/controllers/orders_controller.rb
app/views/cartitems/index.html.erb
app/views/orders/confirm.html.erb

#cartitemに既に同じ商品がある場合は、同じ商品を追加した際は、個数が増えるようにしました。
#order-confirmに入力画面に戻るボタンを追加。

[fix]cartitem&order

---

app/controllers/customers_controller.rb

[fix]withdraw

---

app/views/admins/customers/index.html.erb
app/views/admins/customers/show.html.erb

[fix]admin-customer

---

app/assets/stylesheets/application.scss
app/controllers/items_controller.rb
app/views/admins/_link.html.erb
app/views/customers/_link.html.erb
app/views/items/index.html.erb
app/views/items/show.html.erb
app/views/kaminari/_first_page.html.erb
app/views/kaminari/_gap.html.erb
app/views/kaminari/_last_page.html.erb
app/views/kaminari/_next_page.html.erb
app/views/kaminari/_page.html.erb
app/views/kaminari/_paginator.html.erb
app/views/kaminari/_prev_page.html.erb
app/views/layouts/application.html.erb

[fix]paginator

---

app/views/orders/thanks.html.erb

[fix]thanks
